# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/hexo
image: node:12.18.3

pages:
  script:
    - npm cache clean
    - npm install hexo@5.2.0 -g
    - npm install
    - yarn install
    - hexo g
  artifacts:
    paths:
      - public
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master