language: node_js
node_js: stable

sudo: required

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo clean && hexo g
  - cd ./public
  - git init
  - git config user.name "Open-super"
  - git config user.email "sladmin@slwebtap.onmicrosoft.com"
  - git add .
  - git commit -m "Update"
  - git push --force --quiet "https://pt5anua7q7zz:8f1af28f8d37a7a7edac88caba923018bda6e542@e.coding.net/supermicors/xindeboke_jiudeyifeiqi.git" master:master
  - git push --force --quiet "https://53b54b123cd23bf624a05e7f2cee5c349faf0c80@github.com/slblog-github/Blog.git" master:master

# after_script:

branches:
  only:
    - master