name: Build Blog

on: [push, repository_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Install Nodejs Lib
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Install Hexo Lib
        run: |
          export TZ='Asia/Shanghai'
          npm install hexo-cli -g
          npm install gulp-cli -g
          npm install yuque-hexo -g
          yuque-hexo clean
          yuque-hexo sync
          npm i --save
          npm install highlight.js --save

      - name: Cache to Hexo
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

      - name: Install Other Lib
        run: |
          npm install --save
          npm install highlight.js --save

      - name: Generate and Compression
        run: |
          hexo clean
          hexo g
          gulp

      - name: Deploy Blog in Network
        run: |
          git config --global user.name "slblog-github"
          git config --global user.email "sladmin@slwebtap.onmicrosoft.com"
          git add public/
          git commit -m "Update Blog from GitHub Actions"
          git push --force --quiet https://${{ secrets.USE }}:${{ secrets.PAS }}/slblog-github/Blog.git